version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
        - wpsite
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
    - '8081:80'
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8082:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
       - wpsite
     volumes:
      - ./data:/data
      - ./wp-content/themes/my-theme:/app/wp-content/themes/my-theme
      – ./wp-content/plugins/my-plugin:/app/wp-content/plugins/my-plugin

volumes:
    db_data: {}
networks:
  wpsite:
